# Generated by Django 4.0.2 on 2022-04-30 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_book_cover_book_sample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='sample',
            field=models.FileField(blank=True, null=True, upload_to='book_samples/'),
        ),
    ]
